# Generated by Django 4.0.1 on 2022-01-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='solid',
        ),
    ]
